
export class Charges {
    public static chargesList = [
        'Administration of Justice',
        'Aggravated Assault Police Officer',
        'Aggravated Battery Police Officer',
        'Aggravated Battery With A Firearm',
        'Aggravated Battery',
        'Aggravated Discharge Firearm',
        'Aggravated DUI',
        'Aggravated Fleeing and Eluding',
        'Aggravated Identity Theft',
        'Aggravated Robbery',
        'Antitrust',
        'Armed Robbery',
        'Armed Violence',
        'Arson and Attempt Arson',
        'Arson',
        'Attempt Armed Robbery',
        'Attempt Arson',
        'Attempt First Degree Murder',
        'Attempt Homicide',
        'Attempt Sex Crimes',
        'Attempt Vehicular Hijacking',
        'Battery',
        'Bomb Threat',
        'Bribery',
        'Bribery/Corruption',
        'Burglary',
        'Burglary/Trespass',
        'Child Abduction',
        'Child Pornography',
        'Commercialized Vice',
        'Communicating With Witness',
        'Credit Card Cases',
        'Criminal Damage to Property',
        'Criminal Trespass To Residence',
        'Deceptive Practice',
        'Disarming Police Officer',
        'Dog Fighting',
        'Domestic Battery',
        'Driving With Suspended Or Revoked License',
        'Drug Possession',
        'Drug Trafficking',
        'DUI',
        'Environmental',
        'Escape - Failure to Return',
        'Extortion/Racketeering',
        'FALSIFICATION OF ACCOUNTS',
        'Failure to Register as a Sex Offender',
        'Firearms',
        'Food and Drug',
        'Forgery',
        'Forgery/Counter/Copyright',
        'Fraud',
        'Fraud/Theft/Embezzlement',
        'Fraudulent ID',
        'Gambling',
        'Gun - Non UUW',
        'Gun Running',
        'Hate Crimes',
        'Home Invasion',
        'Homicide',
        'Human Trafficking',
        'Identity Theft',
        'Immigration',
        'Impersonating Police Officer',
        'Intimidation',
        'Invidual Rights',
        'Kidnapping',
        'Major Accidents',
        'Manslaughter',
        'Money Laundering',
        'Murder',
        'Narcotics',
        'National Defense',
        'Obscenity/Other Sex Offenses',
        'Obstructing Justice',
        'Official Misconduct',
        'Other Offense',
        'Other',
        'Pandering',
        'Perjury',
        'Possession Of Burglary Tools',
        'Possession of Contraband in Penal Institution',
        'Possession of Explosives',
        'Possession of Stolen Motor Vehicle',
        'Prison Offenses',
        'PROMIS Conversion',
        'Prostitution',
        'Reckless Discharge of Firearm',
        'Reckless Homicide',
        'Residential Burglary',
        'Retail Theft',
        'REVOKED/SUSPENDED 2ND+ DUI',
        'Robbery',
        'Sex Crimes',
        'SEX WITH ANIMAL/<18 PRESENT',
        'Sexual Abuse',
        'Stalking',
        'Stalking/Harassing',
        'Tampering',
        'Tax',
        'Theft by Deception',
        'Theft',
        'Unlawful Restraint',
        'UUW - Unlawful Use of Weapon',
        'Vehicular Hijacking',
        'Vehicular Invasion',
        'Violate Bail Bond',
        'VIO BAIL BOND/CLASS X CONVIC',
        'Violation of Sex Offender Registration',
        'Violation Order Of Protection'
      ];
}