version: '3'
services:
  python-server:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: backend
    volumes:
       - ../python:/app
  angular-ui:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
    container_name: angular-ui
    # volumes:
    #    - ../client:/usr/share/nginx/html